import type agents from "./data/agents.json";
import type alerts from "./data/alert-inbox.json";
import type rules from "./data/alert-rules.json";
import type approvals from "./data/approvals.json";
import type claims from "./data/claims.json";
import type datasets from "./data/datasets.json";
import type endpoints from "./data/endpoints.json";
import type events from "./data/events.json";
import type evidence from "./data/evidence.json";
import type experiments from "./data/experiment-queue.json";
import type integrations from "./data/integrations.json";
import type models from "./data/models.json";
import type notebooks from "./data/notebooks.json";
import type notifications from "./data/notifications.json";
import type phases from "./data/phases.json";
import type projects from "./data/projects.json";
import type prompts from "./data/prompts.json";
import type registeredModels from "./data/registered-models.json";
import type reports from "./data/reports.json";
import type roles from "./data/roles.json";
import type runs from "./data/runs-history.json";
import type schedules from "./data/schedules.json";
import type workspaces from "./data/workspaces.json";

/** Immutable handoff shapes. These aliases must never be used as production API contracts. */
export type Agent = (typeof agents)[number];
export type Alert = (typeof alerts)[number];
export type AlertRule = (typeof rules)[number];
export type Approval = (typeof approvals)[number];
export type Claim = (typeof claims)[number];
export type Dataset = (typeof datasets)[number];
export type Endpoint = (typeof endpoints)[number];
export type Event = (typeof events)[number];
export type Evidence = (typeof evidence)[number];
export type Experiment = (typeof experiments)[number];
export type Integration = (typeof integrations)[number];
export type Model = (typeof models)[number];
export type Notebook = (typeof notebooks)[number];
export type Notification = (typeof notifications)[number];
export type Phase = (typeof phases)[number];
export type PhaseTask = Phase["tasks"][number];
export type Project = (typeof projects)[number];
export type Prompt = (typeof prompts)[number];
export type RegisteredModel = (typeof registeredModels)[number];
export type Report = (typeof reports)[number];
export type Role = (typeof roles)[number];
export type Run = (typeof runs)[number];
export type Schedule = (typeof schedules)[number];
export type Workspace = (typeof workspaces)[number];
