/** Reference: screens/DataHealth.jsx; EXAMPLE ONLY. */
export const DH_METRICS = [
  {
    id: "d_medqa_zh_v4",
    dataset: "medqa · zh · v4",
    rows: 42800,
    drift: 0.03,
    freshness_d: 2,
    pii_hits: 0,
    label_skew: 0.12,
    schema_ok: true,
  },
  {
    id: "d_medqa_es_v4",
    dataset: "medqa · es · v4",
    rows: 38200,
    drift: 0.14,
    freshness_d: 3,
    pii_hits: 2,
    label_skew: 0.28,
    schema_ok: true,
  },
  {
    id: "d_medqa_ar_v4",
    dataset: "medqa · ar · v4",
    rows: 12400,
    drift: 0.31,
    freshness_d: 12,
    pii_hits: 0,
    label_skew: 0.48,
    schema_ok: false,
  },
  {
    id: "d_adv_ret_v7",
    dataset: "adversarial-retrieval · v7",
    rows: 8400,
    drift: 0.07,
    freshness_d: 1,
    pii_hits: 0,
    label_skew: 0.09,
    schema_ok: true,
  },
  {
    id: "d_steering_v3",
    dataset: "steering-eval · v3",
    rows: 2100,
    drift: 0.02,
    freshness_d: 24,
    pii_hits: 0,
    label_skew: 0.15,
    schema_ok: true,
  },
  {
    id: "d_prompt_inj_v2",
    dataset: "prompt-injection · v2",
    rows: 5600,
    drift: 0.09,
    freshness_d: 6,
    pii_hits: 4,
    label_skew: 0.19,
    schema_ok: true,
  },
];
