/** Reference: screens/Incidents.jsx; EXAMPLE ONLY. */
export const INCIDENTS = [
  {
    id: "inc_2026_0827_a",
    title: "prod-us-east endpoint p95 latency breach (1.2s SLO)",
    severity: "sev2",
    status: "resolved",
    opened_at: "2026-08-27T12:12:00Z",
    resolved_at: "2026-08-27T13:44:00Z",
    duration_min: 92,
    commander: "leo.tanaka@research.io",
    scope: ["endpoint:prod-us-east", "run:run_01K5FZ8G3X2QN4M"],
    impact: "3 runs entered SUPERVISED autonomy; 82 requests degraded",
    rca_cause: "Cold-start capacity in us-east region insufficient after gemini failover",
    action_items: [
      {
        id: "ai_01",
        text: "Add 20% warm-pool headroom in us-east",
        owner: "kai.nakamura",
        status: "in-progress",
        due: "2026-09-05",
      },
      {
        id: "ai_02",
        text: "Alert threshold for cold-start count > 5/min",
        owner: "leo.tanaka",
        status: "done",
        due: "2026-08-29",
      },
      {
        id: "ai_03",
        text: "Playbook: model-failover runbook v2",
        owner: "yui.sato",
        status: "todo",
        due: "2026-09-12",
      },
    ],
    timeline: [
      { at: "12:12", event: "Alert fired · rule=lat.p95>1200ms", actor: "system" },
      { at: "12:14", event: "PagerDuty escalation · commander assumed", actor: "leo.tanaka" },
      { at: "12:22", event: "Root cause identified · cold-start capacity", actor: "kai.nakamura" },
      { at: "12:38", event: "Mitigation · manually scaled warm pool +30%", actor: "kai.nakamura" },
      { at: "13:12", event: "Latency recovered to <400ms p95", actor: "system" },
      { at: "13:44", event: "Incident closed · postmortem opened", actor: "leo.tanaka" },
    ],
  },
  {
    id: "inc_2026_0821_b",
    title: "Run prompt-inj · v3 failed with reviewer capacity exhausted",
    severity: "sev3",
    status: "postmortem",
    opened_at: "2026-08-19T22:14:00Z",
    resolved_at: "2026-08-19T23:02:00Z",
    duration_min: 48,
    commander: "yui.sato@research.io",
    scope: ["run:run_01K51G9K3M1F8P"],
    impact: "8/18 tasks failed to receive human review within SLA",
    rca_cause:
      "Review pool for prompt-injection domain only had 2 qualified reviewers, both offline",
    action_items: [
      {
        id: "ai_04",
        text: "Cross-train 3 additional reviewers for prompt-inj domain",
        owner: "yui.sato",
        status: "in-progress",
        due: "2026-09-30",
      },
      {
        id: "ai_05",
        text: "Auto-downgrade autonomy when review pool < 2 online",
        owner: "leo.tanaka",
        status: "done",
        due: "2026-08-26",
      },
    ],
    timeline: [
      { at: "22:14", event: "Run started · autonomy=SUPERVISED", actor: "system" },
      { at: "22:31", event: "First task awaited review · no reviewer online", actor: "system" },
      { at: "22:55", event: "Reviewer capacity alert · sev3", actor: "system" },
      { at: "23:02", event: "Run failed after 8 tasks timed out", actor: "system" },
    ],
  },
  {
    id: "inc_2026_0817_c",
    title: "Budget cap breach · med-qa project +$680 over cap",
    severity: "sev3",
    status: "open",
    opened_at: "2026-08-17T09:30:00Z",
    resolved_at: null,
    duration_min: null,
    commander: "leo.tanaka@research.io",
    scope: ["project:proj_01K5FZ8G3X2QN4M"],
    impact: "Approval flow triggered; run paused pending PI decision",
    rca_cause: null,
    action_items: [
      {
        id: "ai_06",
        text: "Draft budget forecasting policy for arabic subset",
        owner: "leo.tanaka",
        status: "todo",
        due: "2026-09-02",
      },
    ],
    timeline: [
      { at: "09:30", event: "Budget breach detected · cap=$5000 spent=$5680", actor: "system" },
      { at: "09:31", event: "Run auto-paused, approval requested", actor: "system" },
      { at: "09:45", event: "Awaiting PI review", actor: "system" },
    ],
  },
];
